privoxy: upgraded to 3.0.24

diff --git a/privoxy/privoxy.SlackBuild b/privoxy/privoxy.SlackBuild
--- a/privoxy/privoxy.SlackBuild
+++ b/privoxy/privoxy.SlackBuild
@@ -7,39 +7,35 @@
 # Modified by Corrado Franco for slackers.it repository
 # All rights reserved.
 #
-# Redistribution and use of this script, with or without modification, is
-# permitted provided that the following conditions are met:
-#
-# 1. Redistributions of this script must retain the above copyright
-#    notice, this list of conditions and the following disclaimer.
-#
-# THIS SOFTWARE IS PROVIDED BY THE AUTHOR ''AS IS'' AND ANY EXPRESS OR IMPLIED
-# WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
-# MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO
-# EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
-# SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
-# PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS;
-# OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
-# WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR
-# OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF
-# ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
+# This program is free software: you can redistribute it and/or modify
+# it under the terms of the GNU General Public License as published by
+# the Free Software Foundation; either version 2 of the License, or
+# (at your option) any later version, with the following exception:
+# the text of the GPL license may be omitted.
 
-# Exit on most errors
+# This program is distributed in the hope that it will be useful, but
+# without any warranty; without even the implied warranty of
+# merchantability or fitness for a particular purpose. Compiling,
+# interpreting, executing or merely reading the text of the program
+# may result in lapses of consciousness and/or very being, up to and
+# including the end of all existence and the Universe as we know it.
+# See the GNU General Public License for more details.
+
+# You may have received a copy of the GNU General Public License along
+# with this program (most likely, a file named COPYING).  If not, see
+# <http://www.gnu.org/licenses/>.
+
 set -eu
 
-# Set variables:
 CWD=$(pwd)
 
-PRGNAME=${PRGNAME:-privoxy}
-PKGNAME=${PKGNAME:-$PRGNAME}
-VERSION=${VERSION:-3.0.23}
-PKGVERSION=$(echo $VERSION | tr - _)
+PRGNAM=privoxy
+VERSION=${VERSION:-3.0.24}
 BUILD=${BUILD:-1}
-ARCH=${ARCH:=""} # Set ARCH or leave blank to determine it automatically
 TAG=${TAG:-cf}
 TMP=${TMP:-/tmp/pkg}
-PKG=$TMP/package-$PKGNAME
-DOCS="$PKG/usr/doc/$PKGNAME-$VERSION"
+PKG=$TMP/package-$PRGNAM
+OUTPUT=${OUTPUT:-/tmp}
 
 ## privoxy user & group *MUST* exist before package creation
 # See http://slackbuilds.org/uid_gid.txt for current recomendations.
@@ -47,55 +43,45 @@ PRIVOXY_USER=${PRIVOXY_USER:-privoxy}
 PRIVOXY_GROUP=${PRIVOXY_GROUP:-privoxy}
 
 if ! grep -q ^$PRIVOXY_GROUP: /etc/group 2>/dev/null ; then
-    echo "    Error: PRIVOXY group ($PRIVOXY_GROUP) doesn't exist."
-    echo "    Try creating one with: groupadd -g 206 $PRIVOXY_GROUP"
-    exit 1
+  echo "  Error: PRIVOXY group ($PRIVOXY_GROUP) doesn't exist."
+  echo "  Try creating one with: groupadd -g 206 $PRIVOXY_GROUP"
+  exit 1
 fi
 if ! grep -q ^$PRIVOXY_USER: /etc/passwd 2>/dev/null ; then
-    echo "    Error: PRIVOXY user ($PRIVOXY_USER) doesn't exist."
-    echo "    Try creating one with: useradd -u 206 -g $PRIVOXY_GROUP -d /dev/null -s /bin/false $PRIVOXY_USER"
-    exit 1
+  echo "  Error: PRIVOXY user ($PRIVOXY_USER) doesn't exist."
+  echo "  Try creating one with: useradd -u 206 -g $PRIVOXY_GROUP -d /dev/null -s /bin/false $PRIVOXY_USER"
+  exit 1
 fi
 
-# Automatically determine the architecture we are building on:
-if [ -z "$ARCH" ]; then
-    case "$( uname -m )" in
-        i?86) ARCH=i686 ;;
-        arm*) ARCH=arm ;;
-        # Unless $ARCH is already set, use uname -m for all other archs:
-        *) ARCH=$( uname -m ) ;;
-    esac
+if [ -z ${ARCH:=""} ]; then
+  case "$( uname -m )" in
+  i?86) ARCH=i686 ;;
+  arm*) ARCH=arm ;;
+  *) ARCH=$( uname -m ) ;;
+  esac
 fi
 
-# Set compiling FLAGS
-case "$ARCH" in
-    i486)
-	SLKCFLAGS="-O2 -march=i486 -mtune=i686"; CHOST="i486"
-	SLKLDFLAGS=""; LIBDIRSUFFIX=""
-        ;;
-    i686)
-	SLKCFLAGS="-O2 -march=i686 -pipe -fomit-frame-pointer"; CHOST="i486"
-	SLKLDFLAGS=""; LIBDIRSUFFIX=""
-        ;;
-    x86_64)
-	SLKCFLAGS="-O2 -fPIC -pipe -fomit-frame-pointer"; CHOST="x86_64"
-	SLKLDFLAGS="-L/usr/lib64"; LIBDIRSUFFIX="64"
-        ;;
-    *)
-    SLKCFLAGS="-O2"; CHOST=$ARCH
-    SLKLDFLAGS=""; LIBDIRSUFFIX=""
-	;;
-esac
+if [ "$ARCH" = "i586" ]; then
+  SLKCFLAGS="-O2 -march=i586 -mtune=i686"
+  LIBDIRSUFFIX=""
+elif [ "$ARCH" = "i686" ]; then
+  SLKCFLAGS="-O2 -march=i686 -mtune=i686"
+  LIBDIRSUFFIX=""
+elif [ "$ARCH" = "x86_64" ]; then
+  SLKCFLAGS="-O2 -fPIC -fomit-frame-pointer"
+  LIBDIRSUFFIX="64"
+else
+  SLKCFLAGS="-O2"
+  LIBDIRSUFFIX=""
+fi
 
-# Extract source and prepare:
 rm -rf $PKG
 mkdir -p $TMP $PKG
 cd $TMP
-rm -rf $PRGNAME-$VERSION-stable
+rm -rf $PRGNAM-$VERSION-stable
 tar xvf $CWD/privoxy-$VERSION-stable-src.tar.gz
-cd $PRGNAME-$VERSION-stable
+cd $PRGNAM-$VERSION-stable
 
-# Make sure ownerships and permissions are sane:
 chown -R root:root .
 chmod -R u+w,go+r-w,a-s .
 
@@ -107,27 +93,25 @@ sed -i "/^DOC_DEST/s/= .*/= @docdir@/" GNUmakefile.in
 # Thanks to SBo
 sed -i "s/\[ -s \"\$(CONF_DEST)\/\$\$i\" \]/false/" GNUmakefile.in
 
-# Configure
 autoheader
 autoconf
-LDFLAGS="$SLKLDFLAGS" \
+LDFLAGS="-L/usr/lib$LIBDIRSUFFIX" \
 CFLAGS="$SLKCFLAGS" \
 CXXFLAGS="$SLKCFLAGS" \
 ./configure \
   --prefix=/usr \
-  --libdir=/usr/lib${LIBDIRSUFFIX} \
+  --libdir=/usr/lib$LIBDIRSUFFIX \
   --sysconfdir=/etc/privoxy \
   --localstatedir=/var \
   --mandir=/usr/man \
   --infodir=/usr/info \
-  --docdir=/usr/doc/${PKGNAME}-${VERSION} \
+  --docdir=/usr/doc/$PRGNAM-$VERSION \
   --with-docbook=no \
   --with-user=$PRIVOXY_USER \
   --with-group=$PRIVOXY_GROUP \
-  --host=$CHOST-slackware-linux \
-  --build=$CHOST-slackware-linux
+  --host=$ARCH-slackware-linux \
+  --build=$ARCH-slackware-linux
 
-# Build and install:
 make 
 make DESTDIR=$PKG install-strip
 
@@ -147,27 +131,20 @@ mv $PKG/var/log/privoxy/logfile $PKG/var/log/privoxy/logfile.new
 rmdir $PKG/var/run
 rmdir $PKG/usr/share/
 
-# Compress and link manpages, if any:
 if [ -d $PKG/usr/man ]; then
-( cd $PKG/usr/man
-  find . -type f -exec gzip -9 {} \;
-  for i in $( find . -type l ) ; do ln -s $( readlink $i ).gz $i.gz ; rm $i ; done
-)
+  find $PKG/usr/man -type f -exec chmod 644 {} \; -exec gzip -9 {} \;
+  for i in $( find $PKG/usr/man -type l ) ; do ln -s $( readlink $i ).gz $i.gz ; rm $i ; done
 fi
 
 # Add template for TOR
-install -Dm644 $CWD/config.tor.template $DOCS/config.tor.template
+install -Dm644 $CWD/config.tor.template $PKG/usr/doc/$PRGNAM-$VERSION/config.tor.template
 
-# Add a slackbuild script:
-install -Dm644 $CWD/$PKGNAME.SlackBuild $DOCS/$PKGNAME.SlackBuild
+install -Dm644 $CWD/$PRGNAM.SlackBuild $PKG/usr/doc/$PRGNAM-$VERSION/$PRGNAM.SlackBuild
 
-# Add slack-desc
-install -Dm644 $CWD/slack-desc $PKG/install/slack-desc
+mkdir -p $PKG/install 
+cat $CWD/slack-desc > $PKG/install/slack-desc
+cat $CWD/doinst.sh > $PKG/install/doinst.sh
 
-# Add a doinst.sh
-install -Dm644 $CWD/doinst.sh $PKG/install/doinst.sh
-
-# Create package:
 cd $PKG
-/sbin/makepkg -l y -c n $CWD/$PKGNAME-$PKGVERSION-$ARCH-${BUILD}${TAG}.txz
+/sbin/makepkg -l y -c n $OUTPUT/$PRGNAM-$VERSION-$ARCH-$BUILD$TAG.${PKGTYPE:-txz}
 
