privoxy: rebuilt

diff --git a/privoxy/privoxy.SlackBuild b/privoxy/privoxy.SlackBuild
--- a/privoxy/privoxy.SlackBuild
+++ b/privoxy/privoxy.SlackBuild
@@ -3,8 +3,7 @@
 # Slackware build script for <prgname> (http://www.privoxy.org/)
 #
 # Copyright (c) 2007  alkos333 <me@alkos333.net>
-# Copyright 2009-2015 Corrado Franco (http://conraid.net)
-# Modified by Corrado Franco for slackers.it repository
+# Copyright 2009-2016 Corrado Franco (http://conraid.net)
 # All rights reserved.
 #
 # This program is free software: you can redistribute it and/or modify
@@ -31,7 +30,7 @@ CWD=$(pwd)
 
 PRGNAM=privoxy
 VERSION=${VERSION:-3.0.24}
-BUILD=${BUILD:-1}
+BUILD=${BUILD:-2}
 TAG=${TAG:-cf}
 TMP=${TMP:-/tmp/pkg}
 PKG=$TMP/package-$PRGNAM
@@ -39,25 +38,22 @@ OUTPUT=${OUTPUT:-/tmp}
 
 ## privoxy user & group *MUST* exist before package creation
 # See http://slackbuilds.org/uid_gid.txt for current recomendations.
-PRIVOXY_USER=${PRIVOXY_USER:-privoxy}
-PRIVOXY_GROUP=${PRIVOXY_GROUP:-privoxy}
-
-if ! grep -q ^$PRIVOXY_GROUP: /etc/group 2>/dev/null ; then
-  echo "  Error: PRIVOXY group ($PRIVOXY_GROUP) doesn't exist."
-  echo "  Try creating one with: groupadd -g 206 $PRIVOXY_GROUP"
+if ! grep -q "^privoxy:" /etc/group 2>/dev/null ; then
+  echo "  Error: PRIVOXY group (privoxy) doesn't exist."
+  echo "  Try creating one with: groupadd -g 206 privoxy"
   exit 1
 fi
-if ! grep -q ^$PRIVOXY_USER: /etc/passwd 2>/dev/null ; then
-  echo "  Error: PRIVOXY user ($PRIVOXY_USER) doesn't exist."
-  echo "  Try creating one with: useradd -u 206 -g $PRIVOXY_GROUP -d /dev/null -s /bin/false $PRIVOXY_USER"
+if ! grep -q "^privoxy:" /etc/passwd 2>/dev/null ; then
+  echo "  Error: PRIVOXY user (privoxy) doesn't exist."
+  echo "  Try creating one with: useradd -u 206 -g privoxy -d /dev/null -s /bin/false privoxy"
   exit 1
 fi
 
 if [ -z ${ARCH:=""} ]; then
   case "$( uname -m )" in
-  i?86) ARCH=i686 ;;
-  arm*) ARCH=arm ;;
-  *) ARCH=$( uname -m ) ;;
+    i?86) ARCH=i686 ;;
+    arm*) ARCH=arm ;;
+       *) ARCH=$( uname -m ) ;;
   esac
 fi
 
@@ -68,7 +64,7 @@ elif [ "$ARCH" = "i686" ]; then
   SLKCFLAGS="-O2 -march=i686 -mtune=i686"
   LIBDIRSUFFIX=""
 elif [ "$ARCH" = "x86_64" ]; then
-  SLKCFLAGS="-O2 -fPIC -fomit-frame-pointer"
+  SLKCFLAGS="-O2 -fPIC -pipe -fomit-frame-pointer"
   LIBDIRSUFFIX="64"
 else
   SLKCFLAGS="-O2"
@@ -86,15 +82,14 @@ chown -R root:root .
 chmod -R u+w,go+r-w,a-s .
 
 # Put the docs where we tell them to go.
-sed -i "/^DOC_DEST/s/= .*/= @docdir@/" GNUmakefile.in
+sed '/^DOC_DEST/s/= .*/= @docdir@/' -i GNUmakefile.in
 
 # The Makefile checks if certain config files exist, and if so, adds a
 # .new suffix.  Turn this behavior off.  We will do it below.
 # Thanks to SBo
-sed -i "s/\[ -s \"\$(CONF_DEST)\/\$\$i\" \]/false/" GNUmakefile.in
+sed 's|\[ -s "\$(CONF_DEST)/\$\$i" \]|false|' -i GNUmakefile.in
 
-autoheader
-autoconf
+autoreconf
 LDFLAGS="-L/usr/lib$LIBDIRSUFFIX" \
 CFLAGS="$SLKCFLAGS" \
 CXXFLAGS="$SLKCFLAGS" \
@@ -107,8 +102,11 @@ CXXFLAGS="$SLKCFLAGS" \
   --infodir=/usr/info \
   --docdir=/usr/doc/$PRGNAM-$VERSION \
   --with-docbook=no \
-  --with-user=$PRIVOXY_USER \
-  --with-group=$PRIVOXY_GROUP \
+  --enable-no-gifs \
+  --enable-compression \
+  --with-user=privoxy \
+  --with-group=privoxy \
+  --enable-graceful-termination \
   --host=$ARCH-slackware-linux \
   --build=$ARCH-slackware-linux
 
@@ -120,26 +118,26 @@ install -Dm755 slackware/rc.privoxy $PKG/etc/rc.d/rc.privoxy.new
 
 # Make .new files so we don't clobber the existing configuration.
 # Thanks to SBo
-for i in config match-all.action trust user.action user.filter; do
-  mv $PKG/etc/privoxy/$i $PKG/etc/privoxy/$i.new
+for NEW in config match-all.action trust user.action user.filter; do
+  mv $PKG/etc/privoxy/$NEW $PKG/etc/privoxy/$NEW.new
 done
 
 # Don't clobber the logfile either
 mv $PKG/var/log/privoxy/logfile $PKG/var/log/privoxy/logfile.new
 
 # Remove this directory since it's empty and part of Slackware base
-rmdir $PKG/var/run
-rmdir $PKG/usr/share/
+rmdir $PKG/var/run $PKG/usr/share/
 
 if [ -d $PKG/usr/man ]; then
   find $PKG/usr/man -type f -exec chmod 644 {} \; -exec gzip -9 {} \;
   for i in $( find $PKG/usr/man -type l ) ; do ln -s $( readlink $i ).gz $i.gz ; rm $i ; done
 fi
 
-# Add template for TOR
-install -Dm644 $CWD/config.tor.template $PKG/usr/doc/$PRGNAM-$VERSION/config.tor.template
+mkdir -p $PKG/usr/doc/$PRGNAM-$VERSION
+cat $CWD/$PRGNAM.SlackBuild > $PKG/usr/doc/$PRGNAM-$VERSION/$PRGNAM.SlackBuild
 
-install -Dm644 $CWD/$PRGNAM.SlackBuild $PKG/usr/doc/$PRGNAM-$VERSION/$PRGNAM.SlackBuild
+# Add template for TOR
+cat $CWD/config.tor.template > $PKG/usr/doc/$PRGNAM-$VERSION/config.tor.template
 
 mkdir -p $PKG/install 
 cat $CWD/slack-desc > $PKG/install/slack-desc
