node: upgraded to 4.1.1

diff --git a/node/node.SlackBuild b/node/node.SlackBuild
--- a/node/node.SlackBuild
+++ b/node/node.SlackBuild
@@ -7,145 +7,128 @@
 #
 # All rights reserved.
 #
-# Redistribution and use of this script, with or without modification, is
-# permitted provided that the following conditions are met:
-#
-# 1. Redistributions of this script must retain the above copyright
-#    notice, this list of conditions and the following disclaimer.
-#
-# THIS SOFTWARE IS PROVIDED BY THE AUTHOR ''AS IS'' AND ANY EXPRESS OR IMPLIED
-# WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
-# MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO
-# EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
-# SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
-# PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS;
-# OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
-# WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR
-# OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF
-# ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
+# This program is free software: you can redistribute it and/or modify
+# it under the terms of the GNU General Public License as published by
+# the Free Software Foundation; either version 2 of the License, or
+# (at your option) any later version, with the following exception:
+# the text of the GPL license may be omitted.
+
+# This program is distributed in the hope that it will be useful, but
+# without any warranty; without even the implied warranty of
+# merchantability or fitness for a particular purpose. Compiling,
+# interpreting, executing or merely reading the text of the program
+# may result in lapses of consciousness and/or very being, up to and
+# including the end of all existence and the Universe as we know it.
+# See the GNU General Public License for more details.
+
+# You may have received a copy of the GNU General Public License along
+# with this program (most likely, a file named COPYING).  If not, see
+# <http://www.gnu.org/licenses/>.
 #
 # Initial SlackBuild by Audrius Kažukauskas
 # Rewritten by Corrado Franco for Slackers.it
 #
-# Latest version of this SlackBuild at http://slackers.it/repository
+# Latest version of this SlackBuild at https://github.com/conraid/SlackBuilds
 
-# Exit on most errors
 set -eu
 
-# Set variables:
 CWD=$(pwd)
 
-PRGNAME=${PRGNAME:-node}
-PKGNAME=$(echo ${PRGNAME} | tr A-Z a-z)
-VERSION=${VERSION:-v0.12.7}
-PKGVERSION=${VERSION//-/_}
+PRGNAM=${PRGNAM:-node}
+VERSION=${VERSION:-4.1.1}
 BUILD=${BUILD:-1}
 TAG=${TAG:-cf}
 TMP=${TMP:-/tmp/pkg}
-PKG=${TMP}/package-${PKGNAME}
-PKGDOCDIR="${PKG}/usr/doc/${PKGNAME}-${PKGVERSION}"
+PKG=$TMP/package-$PRGNAM
+OUTPUT=${OUTPUT:-/tmp}
+DOCDIR="$PKG/usr/doc/$PRGNAM-$VERSION"
 
-# Insert document files in this variable
-DOCFILES="AUTHORS CONTRIBUTING* ChangeLog LICENSE README* doc/*"
+DOCFILES="AUTHORS CHANGELOG* CONTRIBUTING* GOVERNANCE* LICENSE README* ROADMAP* WORKING_GROUPS* doc"
 
-# Automatically determine the architecture we're building on:
 if [ -z ${ARCH:=""} ]; then
-    case "$( uname -m )" in
-    i?86) ARCH=i686 ;;
-    arm*) ARCH=arm ;;
-    # Unless ${ARCH} is already set, use uname -m for all other archs:
-    *) ARCH=$( uname -m ) ;;
-    esac
+  case "$( uname -m )" in
+  i?86) ARCH=i686 ;;
+  arm*) ARCH=arm ;;
+  *) ARCH=$( uname -m ) ;;
+  esac
 fi
 
-# Set compiling FLAGS
-case "${ARCH}" in
-    i[3-5]86)
-    SLKCFLAGS="-O2 -march=${ARCH} -mtune=i686"; CHOST="i486"
-    SLKLDFLAGS=""; LIBDIRSUFFIX=""
-    ;;
-    i686)
-    SLKCFLAGS="-O2 -march=i686 -fomit-frame-pointer"; CHOST="i486"
-    SLKLDFLAGS=""; LIBDIRSUFFIX=""
-    ;;
-    x86_64)
-    SLKCFLAGS="-O2 -fPIC -fomit-frame-pointer"; CHOST="x86_64"
-    SLKLDFLAGS="-L/lib64 -L/usr/lib64"; LIBDIRSUFFIX="64"
-    ;;
-    *)
-    SLKCFLAGS="-O2"; CHOST=${ARCH}
-    SLKLDFLAGS=""; LIBDIRSUFFIX=""
-    ;;
-esac
+if [ "$ARCH" = "i586" ]; then
+  SLKCFLAGS="-O2 -march=i586 -mtune=i686"
+  LIBDIRSUFFIX=""
+elif [ "$ARCH" = "i686" ]; then
+  SLKCFLAGS="-O2 -march=i686 -mtune=i686"
+  LIBDIRSUFFIX=""
+elif [ "$ARCH" = "x86_64" ]; then
+  SLKCFLAGS="-O2 -fPIC"
+  LIBDIRSUFFIX="64"
+else
+  SLKCFLAGS="-O2"
+  LIBDIRSUFFIX=""
+fi
 
-# Extract source and prepare:
-rm -rf ${PKG}
-mkdir -p ${TMP} ${PKG}
-cd ${TMP}
-rm -rf ${PRGNAME}-${VERSION}
-tar xvf ${CWD}/${PRGNAME}-${VERSION}.tar.gz
-cd ${PRGNAME}-${VERSION}
+rm -rf $PKG
+mkdir -p $TMP $PKG
+cd $TMP
+rm -rf $PRGNAM-$VERSION
+tar xvf $CWD/$PRGNAM-$VERSION.tar.gz || tar xvf $CWD/v$VERSION.tar.gz
+cd $PRGNAM-$VERSION
 
-# Make sure ownerships and permissions are sane:
 chown -R root:root .
-chmod -R u+w,go+r-w,a-s .
+find . \
+ \( -perm 777 -o -perm 775 -o -perm 750 -o -perm 711 -o -perm 555 \
+  -o -perm 511 \) -exec chmod 755 {} \; -o \
+ \( -perm 666 -o -perm 664 -o -perm 640 -o -perm 600 -o -perm 444 \
+  -o -perm 440 -o -perm 400 \) -exec chmod 644 {} \;
 
 # Fix man page path.
 sed 's|share/man|/man|' -i tools/install.py
 
 # Fix libdir for 64-bit.
-sed "s|\(['/]\)lib/|\1lib${LIBDIRSUFFIX}/|g" -i tools/install.py
-sed "s|'lib'|'lib${LIBDIRSUFFIX}'|" -i lib/module.js
+sed "s|\(['/]\)lib/|\1lib$LIBDIRSUFFIX/|g" -i tools/install.py
+sed "s|'lib'|'lib$LIBDIRSUFFIX'|" -i lib/module.js
+sed "s|\"lib\"|\"lib$LIBDIRSUFFIX\"|"  -i deps/npm/lib/npm.js
 
-# Configure
-LDFLAGS="${SLKLDFLAGS}" \
-CFLAGS="${SLKCFLAGS}" \
-CXXFLAGS="${SLKCFLAGS}" \
+CFLAGS="$SLKCFLAGS" \
+CXXFLAGS="$SLKCFLAGS" \
 ./configure \
   --prefix=/usr \
-  --shared-openssl \
   --shared-zlib \
   --with-intl=system-icu
+# Removed --shared-openssl because build failure with openssl 1.0.1*
 
-# Build and install:
-make CFLAGS="${SLKCFLAGS}" CXXFLAGS="${SLKCFLAGS}" LDFLAGS="${SLKLDFLAGS}"
-make DESTDIR=${PKG} install
+make CFLAGS="$SLKCFLAGS" CXXFLAGS="$SLKCFLAGS" 
+make DESTDIR=$PKG install
 
-# Strip binaries:
-find ${PKG} | xargs file | grep -e "executable" -e "shared object" | grep ELF | cut -f 1 -d : | xargs -r strip --strip-unneeded 2> /dev/null || true
-find ${PKG} | xargs file | grep "current ar archive" | cut -f 1 -d : | xargs -r strip -g 2> /dev/null || true
+find $PKG | xargs file | grep -e "executable" -e "shared object" | grep ELF | cut -f 1 -d : | xargs -r strip --strip-unneeded 2> /dev/null || true
+find $PKG | xargs file | grep "current ar archive" | cut -f 1 -d : | xargs -r strip -g 2> /dev/null || true
 
-# Compress and link manpages, if any:
-if [ -d ${PKG}/usr/man ]; then
-    find ${PKG}/usr/man -type f -exec chmod 644 {} \; -exec gzip -9 {} \;
-    for i in $( find ${PKG}/usr/man -type l ) ; do ln -s $( readlink $i ).gz $i.gz ; rm $i ; done
+if [ -d $PKG/usr/man ]; then
+  find $PKG/usr/man -type f -exec chmod 644 {} \; -exec gzip -9 {} \;
+  for i in $( find $PKG/usr/man -type l ) ; do ln -s $( readlink $i ).gz $i.gz ; rm $i ; done
 fi
 
 # Remove unneeded files.
-find ${PKG}/usr \( -name '.git*' -o -name '.travis.yml' \) -exec rm -f {} \;
+find $PKG/usr \( -name '.git*' -o -name '.travis.yml' \) -exec rm -f {} \;
 
 # Set NODE_PATH to look for globally installed modules.
-mkdir -p ${PKG}/etc/profile.d
-cat > ${PKG}/etc/profile.d/node.csh << EOF
+mkdir -p $PKG/etc/profile.d
+cat > $PKG/etc/profile.d/node.csh << EOF
 #!/bin/csh
-setenv NODE_PATH /usr/lib${LIBDIRSUFFIX}/node_modules
+setenv NODE_PATH /usr/lib$LIBDIRSUFFIX/node_modules
 EOF
-cat > ${PKG}/etc/profile.d/node.sh << EOF
+cat > $PKG/etc/profile.d/node.sh << EOF
 #!/bin/sh
-export NODE_PATH=/usr/lib${LIBDIRSUFFIX}/node_modules
+export NODE_PATH=/usr/lib$LIBDIRSUFFIX/node_modules
 EOF
-chmod 0755 ${PKG}/etc/profile.d/*
+chmod 0755 $PKG/etc/profile.d/*
 
-# Add a documentation directory:
-mkdir -p ${PKGDOCDIR}
-cp -a ${DOCFILES} ${PKGDOCDIR} || true
+mkdir -p $DOCDIR
+cp -a $DOCFILES $DOCDIR || true
+cat $CWD/$PRGNAM.SlackBuild > $DOCDIR/$PRGNAM.SlackBuild
 
-# Add a slackbuild script:
-install -Dm644 ${CWD}/${PKGNAME}.SlackBuild ${PKGDOCDIR}/${PKGNAME}.SlackBuild
+mkdir -p $PKG/install 
+cat $CWD/slack-desc > $PKG/install/slack-desc
 
-# Add slack-desc
-install -Dm644 ${CWD}/slack-desc ${PKG}/install/slack-desc
-
-# Create package:
-cd ${PKG}
-/sbin/makepkg -l y -c n ${CWD}/${PKGNAME}-${PKGVERSION}-${ARCH}-${BUILD}${TAG}.txz
+cd $PKG
+/sbin/makepkg -l y -c n $OUTPUT/$PRGNAM-$VERSION-$ARCH-$BUILD$TAG.${PKGTYPE:-txz}
